name: Run Docker Container

on:
  push:
    branches:
      - main

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set execute permissions for entrypoint
      run: chmod +x entrypoint.sh
      
    - name: Build Docker image
      run: |
        docker build --platform linux/amd64 -t my-docker-image .
        
    - name: Run Docker container
      run: docker run --platform linux/amd64 my-docker-image