name: Extract Folders on Closed PR with "Devin"

on:
  pull_request:
    types: [closed]

jobs:
  extract-folders:
    if: |
      github.event.pull_request.merged == true &&
      (
        contains(github.event.pull_request.title, 'Devin') ||
        contains(github.event.pull_request.title, 'devin') ||
        contains(github.event.pull_request.body, 'Devin') ||
        contains(github.event.pull_request.body, 'devin')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract top-level folders from PR files
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching files changed in PR #$PR_NUMBER"
          files=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/files" | \
            jq -r '.[].filename' | awk -F'/' '{print $1}' | sort -u)
          if [ -n "$files" ]; then
            echo "Top-level folders changed in PR:"
            echo "$files"
          else
            echo "No folders found or error fetching PR files"
            exit 1
          fi