name: Extract Folders on Closed PR with "Devin"

on:
  pull_request:
    types: [closed]

jobs:
  extract-folders:
    if: |
      github.event.pull_request.merged == true &&
      (
        contains(github.event.pull_request.title, 'Devin') ||
        contains(github.event.pull_request.title, 'devin') ||
        contains(github.event.pull_request.body, 'Devin') ||
        contains(github.event.pull_request.body, 'devin')
      )
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.extract.outputs.folders }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract top-level folders from PR files
        id: extract
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching files changed in PR #$PR_NUMBER"
          files=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/files" | \
            jq -r '.[].filename' | awk -F'/' '{print $1}' | sort -u)
          if [ -n "$files" ]; then
            echo "Top-level folders changed in PR:"
            echo "$files"
            folders_json=$(echo "$files" | jq -R -s -c 'split("\n") | map(select(length > 0))')
            echo "folders=$folders_json" >> $GITHUB_OUTPUT
          else
            echo "No folders found or error fetching PR files"
            exit 1
          fi

  run-script-in-folders:
    needs: extract-folders
    runs-on: ubuntu-latest
    if: ${{ needs.extract-folders.outputs.folders != '[]' && needs.extract-folders.outputs.folders != '' }}
    strategy:
      matrix:
        folder: ${{ fromJson(needs.extract-folders.outputs.folders) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script.js in folder
        run: |
          if [ -f "${{ matrix.folder }}/script.js" ]; then
            echo "Running script.js in ${{ matrix.folder }}"
            node "${{ matrix.folder }}/script.js"
          else
            echo "No script.js found in ${{ matrix.folder }}"
          fi